//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_details
    {
        public int BillId { get; set; }
        public System.DateTime BillDate { get; set; }
        public int Seller { get; set; }
        public int Amount { get; set; }
    
        public virtual Seller_details Seller_details { get; set; }
    }
}
