//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Seller_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller_details()
        {
            this.Billing_details = new HashSet<Billing_details>();
        }
        
        public int SelId { get; set; }
        public string SelName { get; set; }
        public string SelEmail { get; set; }
        public string SelPwd { get; set; }
        public System.DateTime SelDOB { get; set; }
        public string SelGen { get; set; }
        public string SelAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing_details> Billing_details { get; set; }
    }
}
